### PR TITLE
[WIP] docker and docker-compose for development and open-source

### PR DESCRIPTION
**Pull request by mkurek**
Tipboard sources:
- fixed creating project when .tipboard directory exists

Docker:
- added docker config files
- added docker-compose config files
- added readme with basic steps for development and open-source environment

### CODE REVIEW

**Comment by mkurek** [comment]
TODO:

[ ] fix running unit tests (`OSError: [Errno 16] Device or resource busy` when trying to rename .tipboard directory)
[ ] test usecases from readme

**Comment by vi4m** [comment]
nicely done.

**Comment by szok** [comment]
:+1:

**Comment by ar4s** [comment]
:ok:

**Comment by vi4m** [comment]
Do we wait for something?

**Comment by mkurek** [comment]
yes - unit tests are not working in docker right now

**Pull request closed without merging**
