### PR TITLE
Merge with Python3.7 & Django2 + Openshift compatible

### PR DESCRIPTION
**Pull request by the-maux**
* Migrate Python2.7 to Python3.7 and upgrading all python library
    * Removed libraries:
        * mock==1.0.1
        * requests==1.2.3
        * six>=1.4.1
        * tornado-redis==2.4.2
        * tornado==3.0.1
        * docopt==0.6.1
        * raven==3.5.2
        * Sphinx==1.2.2
        * sphinxcontrib-httpdomain==1.3.0

    * Added libraries:
        * django>=2.2.1
        * django-prometheus>=1.0.15
        * django-cors-headers>=3.0.1
        * channels>=2.2.0
        * channels_redis>=2.4.0
        * asgiref>=3.1.4

* Using Django2.0 over tornado now
    * Updating tornado template tiles-.html to template django, moving them in templates directory
    * Using channels_redis.core.RedisChannelLayer over tornadoredis
    * Using channels.generic.websocket over tornado.websocket.WebSocketHandler
    * Using static files from django behavior over tornado.web.StaticFileHandler
    * Moving tornado url routing behavior to the django behavior
    * removing duplicate inner function to a single file utils.py
    * reworking of the file redis_utils.py to a cache.py
    * Config for ASGI_APPLICATION

* Moving the .tipboard directory to ./tipboard/Config/ to make it compatible with bitnami/python
* Adding dockerfile support
    * Using bitnami image in order to be cloud ready
    * Using non root image
* Adding .gitlab-ci to CI with gitlab
* Adding .travis.yml to CI with github
* Minor fixes, improvements, cleanups etc.

### CODE REVIEW

**Comment by the-maux** [comment]
Closing, cause of some bug during the merge
I will re-open when fixed

**Comment by alexyak1** [comment]
I have check that you added docker for Tipboard. And as I understood one container for everything. It will be good keep every services in different containers. Redis and framework

**Comment by alexyak1** [comment]
> Closing, cause of some bug during the merge
> I will re-open when fixed

I have check that you added docker for Tipboard. And as I understood one container for everything. It will be good keep every services in different containers. Redis and framework

**Comment by the-maux** [comment]
I wanted to let the user choose.
By default there is a redis inside, if you want to externalise the service, you just have to:
- In Dockerfile Comment the line 3 `RUN apt-get update && apt-get install redis-server -y` 
- In entrypoint.sh Comment the line 2 `nohup redis-server &`
- Change the value **REDIS_HOST** **REDIS_PASSWORD** in the tipboard/Config/properties.json (and password ofc)
I plan to make an example of it

By the way i did a new PR #70

**Pull request closed without merging**
